import { relations, sql } from 'drizzle-orm';
import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
import { makeId } from '../lib/makeId';

export const strategy = sqliteTable('strategy', {
  id: text('id').primaryKey().$default(() => makeId()),
  name: text('name').notNull(),
  type: text('type', { enum: ['base', 'unit'] }).notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const elfFile = sqliteTable('elf_file', {
  id: text('id').primaryKey().$default(() => makeId()),
  filename: text('filename').notNull(),
  s3FileId: text('s3_file_id').notNull(),
  strategyId: text('strategy_id')
    .notNull()
    .references(() => strategy.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const strategyGroup = sqliteTable('strategy_group', {
  id: text('id').primaryKey().$default(() => makeId()),
  name: text('name').notNull(),
  status: text('status', { enum: ['normal', 'disabled', 'banned', 'deleted'] }).default('disabled').notNull(),
  strategyBaseId: text('strategy_base_id')
    .notNull()
    .references(() => strategy.id, { onDelete: 'cascade' }),
  strategyUnitId: text('strategy_unit_id')
    .notNull()
    .references(() => strategy.id, { onDelete: 'cascade' }),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  elo: integer('elo').default(1500).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const eloHistory = sqliteTable('elo_history', {
  id: text('id').primaryKey().$default(() => makeId()),
  strategyGroupId: text('strategy_group_id')
    .notNull()
    .references(() => strategyGroup.id, { onDelete: 'cascade' }),
  elo: integer('elo').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
});

export const match = sqliteTable('match', {
  id: text('id').primaryKey().$default(() => makeId()),
  strategyGroupAId: text('strategy_group_a_id')
    .notNull()
    .references(() => strategyGroup.id, { onDelete: 'cascade' }),
  strategyGroupBId: text('strategy_group_b_id')
    .notNull()
    .references(() => strategyGroup.id, { onDelete: 'cascade' }),
  status: text('status', { enum: ['pending', 'running', 'completed'] }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
});

export const replayFile = sqliteTable('replay_file', {
  id: text('id').primaryKey().$default(() => makeId()),
  filename: text('filename').notNull(),
  s3FileId: text('s3_file_id').notNull(),
  matchId: text('match_id')
    .notNull()
    .references(() => match.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

// User related schema generated by BetterAuth

export const user = sqliteTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' })
    .default(false)
    .notNull(),
  image: text('image'),
  strategyGroupLimit: integer('strategy_group_limit').default(3).notNull(),
  strategyLimit: integer('strategy_limit').default(5).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = sqliteTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    token: text('token').notNull().unique(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  table => [index('session_userId_idx').on(table.userId)],
);

export const account = sqliteTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: integer('access_token_expires_at', {
      mode: 'timestamp_ms',
    }),
    refreshTokenExpiresAt: integer('refresh_token_expires_at', {
      mode: 'timestamp_ms',
    }),
    scope: text('scope'),
    password: text('password'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  table => [index('account_userId_idx').on(table.userId)],
);

export const verification = sqliteTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  table => [index('verification_identifier_idx').on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  strategies: many(strategy),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

export const strategyRelations = relations(strategy, ({ one }) => ({
  user: one(user, {
    fields: [strategy.userId],
    references: [user.id],
  }),
  elfFile: one(elfFile),
}));

export const elfFileRelations = relations(elfFile, ({ one }) => ({
  strategy: one(strategy, {
    fields: [elfFile.strategyId],
    references: [strategy.id],
  }),
}));

export const strategyGroupRelations = relations(strategyGroup, ({ one }) => ({
  user: one(user, {
    fields: [strategyGroup.userId],
    references: [user.id],
  }),
  strategyBase: one(strategy, {
    fields: [strategyGroup.strategyBaseId],
    references: [strategy.id],
  }),
  strategyUnit: one(strategy, {
    fields: [strategyGroup.strategyUnitId],
    references: [strategy.id],
  }),
}));

export const eloHistoryRelations = relations(eloHistory, ({ one }) => ({
  strategyGroup: one(strategyGroup, {
    fields: [eloHistory.strategyGroupId],
    references: [strategyGroup.id],
  }),
}));

export const matchRelations = relations(match, ({ one }) => ({
  strategyGroupA: one(strategyGroup, {
    fields: [match.strategyGroupAId],
    references: [strategyGroup.id],
  }),
  strategyGroupB: one(strategyGroup, {
    fields: [match.strategyGroupBId],
    references: [strategyGroup.id],
  }),
  replayFile: one(replayFile),
}));

export const replayFileRelations = relations(replayFile, ({ one }) => ({
  match: one(match, {
    fields: [replayFile.matchId],
    references: [match.id],
  }),
}));
